version: '3.7'

services:
  store-manager-ui: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8086:80"

networks:
  smu:
    external: true